export const CALCULATOR_REFERENCES: Record<string, Record<string, string>> = {
    INVESTMENT: {
        SIP: "https://groww.in/calculators/sip-calculator",
        LUMPSUM: "https://groww.in/calculators/lumpsum-calculator",
        SWP: "https://groww.in/calculators/swp-calculator",
        MUTUAL_FUND_RETURNS: "https://groww.in/calculators/mutual-fund-returns-calculator",
        STEP_UP_SIP: "https://groww.in/calculators/step-up-sip-calculator",
        CAGR: "https://groww.in/calculators/cagr-calculator",
        XIRR: "https://groww.in/calculators/xirr-calculator",
        ELSS: "https://cleartax.in/s/elss-calculator",
        LTCG: "https://cleartax.in/s/ltcg-calculator",
        STOCK_AVERAGE: "https://groww.in/calculators/stock-average-calculator",
    },
    TAXATION: {
        INCOME_TAX: "https://groww.in/calculators/income-tax-calculator",
        GST: "https://groww.in/calculators/gst-calculator",
        TDS: "https://groww.in/calculators/tds-calculator",
        HRA: "https://groww.in/calculators/hra-calculator",
        ADVANCE_TAX: "https://cleartax.in/s/advancetaxcalculator",
        TAX_SAVING: "https://cleartax.in/s/tax-saving-calculator",
    },
    BANKING_LOANS: {
        EMI: "https://groww.in/calculators/emi-calculator",
        HOME_LOAN_EMI: "https://groww.in/calculators/home-loan-emi-calculator",
        CAR_LOAN_EMI: "https://groww.in/calculators/car-loan-emi-calculator",
        EDUCATION_LOAN_EMI: "https://cleartax.in/s/education-loan-emi-calculator",
        FD: "https://groww.in/calculators/fd-calculator",
        RD: "https://groww.in/calculators/rd-calculator",
        PPF: "https://groww.in/calculators/ppf-calculator",
        SUKANYA_SAMRIDDHI: "https://groww.in/calculators/sukanya-samriddhi-yojana-calculator",
        NSC: "https://groww.in/calculators/nsc-calculator",
        SCSS: "https://groww.in/calculators/scss-calculator",
        KVP: "https://cleartax.in/s/kvp-kisan-vikas-patra-calculator",
        GOLD_LOAN: "https://cleartax.in/s/gold-loan-calculator",
    },
    RETIREMENT_SALARY: {
        EPF: "https://groww.in/calculators/epf-calculator",
        NPS: "https://groww.in/calculators/nps-calculator",
        GRATUITY: "https://groww.in/calculators/gratuity-calculator",
        APY: "https://groww.in/calculators/apy-calculator",
        RETIREMENT: "https://groww.in/calculators/retirement-calculator",
        SALARY: "https://groww.in/calculators/salary-calculator",
        SALARY_HIKE: "https://cleartax.in/s/salary-hike-calculator",
        LEAVE_ENCASHMENT: "https://cleartax.in/s/leave-encashment-calculator",
    },
    MISC: {
        SIMPLE_INTEREST: "https://groww.in/calculators/simple-interest-calculator",
        COMPOUND_INTEREST: "https://groww.in/calculators/compound-interest-calculator",
        INFLATION: "https://groww.in/calculators/inflation-calculator",
        BROKERAGE: "https://groww.in/calculators/brokerage-calculator",
        MARGIN: "https://groww.in/calculators/margin-calculator",
        DEPRECIATION: "https://cleartax.in/s/depreciation-calculator",
        DISCOUNT: "https://cleartax.in/s/discount-calculator",
        NET_WORTH: "https://cleartax.in/s/net-worth-calculator",
        NPV: "https://cleartax.in/s/npv-calculator",
        FUTURE_VALUE: "https://cleartax.in/s/future-value-calculator",
        PRESENT_VALUE: "https://cleartax.in/s/present-value-calculator",
    }
};
